-- Create a public view exposing artist details for published profiles
CREATE OR REPLACE VIEW public.artist_details_public AS
SELECT
  id,
  member_id,
  slug,
  artistic_name,
  full_name,
  profile_text2,
  visao_geral_titulo,
  historia_titulo,
  carreira_titulo,
  mais_titulo,
  biography1,
  profile_image,
  video_banner_landscape,
  video_banner_portrait,
  audio,
  country_residence,
  city,
  facebook,
  instagram,
  youtube_channel,
  music_spotify_apple,
  website,
  link_to_video,
  link_to_video2,
  link_to_video3,
  link_to_video4,
  link_to_video5,
  link_to_video6,
  link_to_video7,
  link_to_video8,
  link_to_video9,
  link_to_video10,
  image1,
  image1_text,
  image2,
  image2_text,
  image3,
  image3_text,
  image4,
  image4_text,
  image5,
  image5_text,
  image6,
  image6_text,
  image7,
  image7_text,
  image8,
  image8_text,
  image9,
  image9_text,
  image10,
  image10_text,
  image11,
  image11_text,
  image12,
  image12_text,
  perfil_completo,
  created_at,
  updated_at
FROM public.new_artist_details
WHERE perfil_completo IS TRUE;

ALTER VIEW public.artist_details_public OWNER TO postgres;
GRANT SELECT ON public.artist_details_public TO anon, authenticated;
